### ISSUE TITLE
Cancel subscription

### ISSUE THREAD

**Issue by RoyGilad** [alfasin/Bluesnap-API#1]
Hi Nir,
I tried to cancel a subscription using the API but got 403, invoked the following:

Method: PUT 
https://ws.bluesnap.com/services/<version>/subscriptions/656565

Body:
<subscription xmlns="http://ws.plimus.com">
      <status>C</status>
      <underlying-sku-id>656565</underlying-sku-id>
      <shopper-id>121212</shopper-id>
</subscription>

Can you help?
Thanks,
Roy

**Comment by alfasin** [comment]
Hi Roy,

Sorry for the late response, I'm subscribed to too many repos in github and getting hundreds of mails and this one must have slipped through my filtering system...

The body of your message is illegal, it should contain a valid XML with all the relevant details.
You can see the following example here: http://docs.bluesnap.com/payment-api/services/subscriptions/update-subscription

```
curl -v -X PUT https://sandbox.bluesnap.com/services/2/subscriptions/39469016 \
-H 'Content-Type: application/xml' \
-H 'Authorization: Basic dXNlcm5hbWU6cGFzc3dvcmQ=' \
-d '
<subscription xmlns="http://ws.plimus.com">
  <subscription-id>39469016</subscription-id>
  <status>A</status>
  <underlying-sku-id>2178834</underlying-sku-id>
  <shopper-id>19505364</shopper-id>
  <auto-renew>true</auto-renew>
</subscription>'
```

Good luck!
N
